import { type InsertTimelineEvent } from "./schema";

export const DEFAULT_EVENTS: InsertTimelineEvent[] = [
  {
    id: "evt-001",
    title: "AGI reaches human-level performance",
    startMonth: "2027-03",
    endMonth: "2028-06",
    category: "AI & Robotics",
    region: "Global",
    suggestedProb: 65,
    yourProb: 75,
    effectiveProb: 75,
    description:
      "Major AI labs release models that score equivalent to human experts on a broad suite of reasoning and creativity tasks.",
    rationale: "Advanced scaling laws and specialized inference hardware breakthroughs.",
    planningPrompts: "How will your workforce adapt? What IP risks does this introduce?",
    sources: [
      { title: "FutureTimeline Report", url: "#" },
      { title: "AI Index 2025", url: "#" },
    ],
  },
  {
    id: "evt-002",
    title: "Commercial Fusion Pilot Plant",
    startMonth: "2032-01",
    endMonth: "2034-12",
    category: "Science & Technology",
    region: "EU",
    suggestedProb: 40,
    yourProb: 55,
    effectiveProb: 55,
    description: "ITER achieves first plasma with net energy gain sustained for >10 minutes.",
    rationale: "Successful magnetic confinement tests in smaller tokamaks.",
    planningPrompts:
      "Investigate long-term energy contracts. Re-evaluate carbon footprint goals.",
    sources: [{ title: "Nature Energy", url: "#" }],
  },
  {
    id: "evt-003",
    title: "First Human Mission to Mars (Departure)",
    startMonth: "2031-09",
    endMonth: "2031-10",
    category: "Space",
    region: "USA",
    suggestedProb: 55,
    yourProb: 60,
    effectiveProb: 60,
    description: "NASA/SpaceX joint mission launches during the 2031 transfer window.",
    planningPrompts: "PR opportunities? Satellite infrastructure expansion?",
    sources: [{ title: "NASA Press Release", url: "#" }],
  },
  {
    id: "evt-004",
    title: "Global Carbon Tax Implementation",
    startMonth: "2028-01",
    endMonth: "2029-12",
    category: "Society & Policy",
    region: "Global",
    suggestedProb: 30,
    yourProb: 45,
    effectiveProb: 45,
    description: "Major economies agree to a unified carbon pricing mechanism.",
    rationale: "Climate feedback loops accelerate political will.",
    planningPrompts: "Audit supply chain carbon costs immediately.",
    sources: [{ title: "UN IPCC", url: "#" }],
  },
  {
    id: "evt-005",
    title: "Level 5 Autonomous Driving Legalized",
    startMonth: "2026-08",
    endMonth: "2027-02",
    category: "AI & Robotics",
    region: "USA",
    suggestedProb: 80,
    yourProb: 85,
    effectiveProb: 85,
    description:
      "Federal legislation passes allowing fully driverless vehicles on all public roads without geofencing.",
    planningPrompts: "Logistics fleet automation strategy?",
    sources: [{ title: "DOT Report", url: "#" }],
  },
  {
    id: "evt-006",
    title: "Synthetic Meat Reaches Price Parity",
    startMonth: "2026-11",
    category: "Environment",
    region: "Global",
    suggestedProb: 75,
    yourProb: 80,
    effectiveProb: 80,
    description:
      "Lab-grown beef becomes cheaper than traditional agriculture beef in major supermarkets.",
    sources: [{ title: "Food Tech Daily", url: "#" }],
  },
  {
    id: "evt-007",
    title: "Neuralink Consumer Release",
    startMonth: "2029-05",
    category: "Science & Technology",
    region: "USA",
    suggestedProb: 45,
    yourProb: 50,
    effectiveProb: 50,
    description: "First non-medical brain-computer interface available for general public.",
    sources: [{ title: "TechCrunch", url: "#" }],
  },
  {
    id: "evt-008",
    title: "Arctic Blue Ocean Event",
    startMonth: "2030-09",
    category: "Environment",
    region: "Global",
    suggestedProb: 60,
    yourProb: 70,
    effectiveProb: 70,
    description: "First ice-free summer in the Arctic.",
    sources: [{ title: "NOAA", url: "#" }],
  },
  {
    id: "evt-009",
    title: "Universal Basic Income Pilot (EU)",
    startMonth: "2027-01",
    endMonth: "2030-01",
    category: "Society & Policy",
    region: "EU",
    suggestedProb: 50,
    yourProb: 55,
    effectiveProb: 55,
    description: "EU launches coordinated UBI pilot across 5 member states.",
    planningPrompts: "Labor market implications? Consumer demand shifts?",
    sources: [{ title: "EU Commission", url: "#" }],
  },
  {
    id: "evt-010",
    title: "Quantum-Proof Encryption Mandated",
    startMonth: "2028-06",
    category: "Science & Technology",
    region: "Global",
    suggestedProb: 35,
    yourProb: 45,
    effectiveProb: 45,
    description: "Major regulators require migration to post-quantum cryptography for critical infrastructure.",
    planningPrompts: "Assess crypto agility of all systems.",
    sources: [{ title: "NIST", url: "#" }],
  },
];
